version: '3.8'

volumes:
  pg_data_production:
  backend_static:
  backend_media:
  frontend_build:

services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: harrowsdocker/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/collected_static
      - backend_media:/app/media

  frontend:
    image: harrowsdocker/foodgram_frontend:latest
    restart: "no"
    volumes:
      - frontend_build:/var/html/frontend

  gateway:
    image: harrowsdocker/foodgram_gateway:latest
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "7000:80"
    volumes:
      - backend_static:/var/html/static
      - backend_media:/var/html/media
      - frontend_build:/var/html/frontend