version: '3.9'

services:
  db:
    image: postgres:16
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_net

  backend:
    build:
      context: ../backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - backend_static:/app/collected_static
      - backend_media:/app/media
    networks:
      - foodgram_net

  frontend:
    build:
      context: ../frontend
    command: sh -c "npm install && npm run build"
    volumes:
      - frontend_build:/app/build
    networks:
      - foodgram_net

  nginx:
    image: nginx:1.27
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
      - backend_static:/var/html/static:ro
      - backend_media:/var/html/media:ro
    networks:
      - foodgram_net

volumes:
  pg_data:
  backend_static:
  backend_media:
  frontend_build:

networks:
  foodgram_net:
